services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contractis
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:rw
      - ./document:/app/document:ro
    env_file: .env
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - DB_PATH=/app/data/contractis.db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      retries: 3
      start_period: 40s
      timeout: 30s
    networks:
      - contractis-network

networks:
  contractis-network:
    driver: bridge